### ISSUE TITLE
Write Rust encoder-decoder in new repo (sequent-core)

### ISSUE THREAD

**Issue by Findeton** [sequentech/roadmap#2]
An encoder/decoder is already implemented in multiple langs: python, js, C++. We also have a battery of tests. We need a Rust implementation + tests to be used in the new release everywhere. [See encoding doc](https://sequentech.github.io/documentation/docs/general/reference/ballot-encoding). We will probably need to use rust features to compile parts of it.

PRs:

- https://github.com/sequentech/sequent-core/pull/12

**Comment by edulix** [comment]
This is done
